# Generated by Django 4.1.5 on 2023-01-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"verbose_name_plural": "Pet"},
        ),
    ]
