# Generated by Django 4.1.5 on 2023-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets_app", "0002_alter_pet_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="pet_mood",
            field=models.TextField(default="happy"),
        ),
    ]
